### ISSUE TITLE
https://github.com/blessedjasonmwanza/ecommerce-rating

### ISSUE THREAD

**Issue by blessedjasonmwanza** [blessedjasonmwanza/ecommerce-rating#22]
## Project Link:  https://github.com/blessedjasonmwanza/ecommerce-rating
This project has 2 collaborators namely: 
- @blessedjasonmwanza 
- @ntazelo 

> 👀  Feel free to check out our Project Kanban [here](https://github.com/blessedjasonmwanza/ecommerce-rating/projects/1)

**Comment by helman101** [comment]
## STATUS: INVALID 🔴 ⚠️ 

Hi @blessedjasonmwanza 😢, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the link to the project, you just include the names of persons working on this project, please add the link too 😄 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

![crab](https://media.giphy.com/media/CoND5j6Bn1QZUgm1xX/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by blessedjasonmwanza** [comment]
Hello, @helman101 ,

Thank you for that awesome catchy review. We have included our project link in the description as guided 🤓 .

> HappyCoding 👨🏽‍💻

**Comment by helman101** [comment]
# STATUS: APPROVED 🟢 🥳 

Hi @blessedjasonmwanza & @ntazelo  🥇 , 

### Congratulations!!! 🥳 🎉

You have successfully completed all the expectations for this project, there is nothing more to do here, now you can go on your way and keep improving your skills.

Cheers and Happy coding!👏👏👏

![gif](https://media.giphy.com/media/3o6fJ1BM7R2EBRDnxK/giphy.gif)

If anything is not 100% clear please leave your questions or comments in the PR thread, we will be glad to help you 😄.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
